name: Laravel CI
on:
  push:
    branches:
      - dev-refractoring-mysql
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.4
    - name: Install Composer
      run:
        composer install
    - name: Setup Laravel Environment
      env:
        APP_KEY: ${{ secrets.APP_KEY }}
      run: |
        cp .env.example .env
        echo "APP_KEY=$APP_KEY" >> .env
    - name: Laravel Test
      run:
        php artisan test
